DROP TABLE IF EXISTS contract CASCADE;
DROP TABLE IF EXISTS local_user CASCADE;
DROP TABLE IF EXISTS organization CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS request CASCADE;
DROP TABLE IF EXISTS user_group CASCADE;